---
title: "Troubleshooting Shiny App: Update Network Plots"
format: html
---



# Set up

Set up packages and list of igraph objects

```{r packages}
# language: r
# plot_comparable_networks_tidy.R
library(tidyverse)
library(igraph)
library(cowplot) # for arranging grid output
library(viridis) # for color scales
library(scales)
library(here)
library(tidygraph)
library(ggraph)
library(grid)
library(RColorBrewer)
library(stringr)
library(magick)

source(here::here('R/color_network_nodes.R'))
```

## User Inputs
calls the following functions:
```{r}

#source("R/generate_participation_network.R") # this function is for vessel-level networks, summarized at the port or state scale
#source("R/color_network_nodes.R")
#source("R/network_stats_functions.R")
#source("R/calc_network_stats.R")
```
<br>

# User Inputs 

Select your directories.
```{r}
## location of fish ticket with metiers assigned, metier key for each port group
indir = '/Users/ana.guerra/Documents/CONFIDENTIAL/Outputs/CCIEA Networks'

## output directory for igraph objects
outdir_ports = 'data/networks/participation_vessel_ports/igraph_test'
# outdir_states = 'data/networks/participation_vessel_states'

## output directory for network viz
pngdir_ports = 'data/networks/participation_vessel_ports/plots_test'
# pngdir_states = 'data/networks/participation_vessel_states/plots'

## output file (including directory) for stat summaries
statdir = 'results/statistics/test'

## directory for species group key. not confidential
processdir <- "data/input"
```

```{r}
#species naming key
myfile5 <- "spgrpn2_iea_key.csv"
```


```{r}

most_recent_igraph <- '2026-03-10'


years <- seq(2020, 2021)

## IOPAC port groups
myports <- c("Monterey", "Puget Sound") # testing script, 
# wa_ports <- myports[1:4]
# or_ports <- myports[5:10]
# ca_ports <- myports[11:20]

## west coast states
mystates <- c("C", "O","W")

```

```{r}
rm_crab = TRUE

vessel_cutoff <- 3
contr_cutoff <- 0.10


## the value of `k` for the k-nearest neighbor function
k <- 1

## the reference years first run through infomap
## for the cciea network analysis this does not matter because we use a prior sp groupings
ref_years <- c(2004,2005)


```


# OLD APPROACH



```{r}
for(y in years){
  if(y %in% ref_years){
    tmptix <- read.csv(paste0(indir,"/fish_tickets_crab", y, "_processed_for_networks_", most_recent_igraph,".csv"), stringsAsFactors = FALSE) %>%
    filter(IOPAC %in% myports)
  } else{
    tmptix <- read.csv(paste0(indir,"/fish_tickets_crab", y, "_processed_for_networks_", most_recent_igraph,".csv"), stringsAsFactors = FALSE) %>%
    filter(IOPAC %in% myports)
  }
  if(exists('fishtix')){
    fishtix <- rbind(fishtix, tmptix)
  } else{ fishtix <- tmptix }
}
rm(tmptix)

# some checks on species groups
unique(fishtix$SPGRPN2)
length(which(is.na(fishtix$SPGRPN2)))
unique(fishtix[which(is.na(fishtix$SPGRPN2)),]$spid)
unique(fishtix[which(is.na(fishtix$SPGRPN2)),]$year)
unique(fishtix[which(is.na(fishtix$SPGRPN2)),]$agid)
unique(fishtix[which(is.na(fishtix$SPGRPN2)),]$pcid)

```
```{r}
fishtix$tdate <- date(parse_date_time(fishtix$tdate, orders=c("ymd", "mdy")))
fishtix$SPGRPN2 = as.character(fishtix$SPGRPN2)
```

```{r}
node_names <- read_csv(here::here(processdir,myfile5),
                       col_types = list(col_character(), col_character(), col_character()))
```

```{r}
total_rev_cutoff <- 5000
indiv_rev_cutoff <- 500
edgetype <- "connectivity"
```

## Functions: 
```{r}
#' Generate Participation Network
#'
#' Create a vessel-level fisheries participation network. Based on original
#' function by Emma Fuller; edits specified in comments.
#'
#' @param tickets fish tickets data frame
#' @param edge_type type of edge weighting to use - the connectivity statistic ("connectivity"), or just number of vessels ("vessels")
#' @param pcid_choose specify an IOPAC port group
#' @param state_choose specify a US West Coast State
#' @param year_choose Specify a crab year
#' @param filter use the `min_vessels` and `min_contribution` objects to filter the data
#' @param filter_subgraph a filtering option from the original function that was turned off for Fisher et al.
#' @param min_vessels the minimum number of vessels participating in a fishery for that fishery to be retained in the network
#' @param min_contribution the minimum contribution (as a proportion) to total exvessel revenue across all vessels for a fishery to be retained in the network
#' @param min_rev the minimum revenue (in dollars) generated from all fisheries for a given vessel in a given year
#' @param min_rev_indiv the minimum revenue (in dollars) generated from any one fishery for a given vessel in a given year
#' @param write_out specify whether to write out the adjacency matrix A that is used to build the graph. not yet coded in below, will make it easier if you want to manually adjust the igraph vertex / edge attributes later.
#' @return non-confidential fisheries partition network as an igraph object
#' @examples
#' close_g <- participation_network_crabyear(close_dat, filter = TRUE, filter_subgraph = FALSE)
#' @export

participation_network_crabyear <- function(
  tickets,
  edge_type = "connectivity",
  pcid_choose = NA,
  state_choose = NA,
  year_choose = NA,
  filter,
  filter_subgraph,
  min_vessels = 3,
  min_contribution = 0.10,
  min_rev = 1,
  min_rev_indiv = 1,
  write_out,
  out_dir
) {
  if (!is.na(state_choose)) {
    tickets = dplyr::filter(tickets, agid %in% state_choose) # updated 08-20-21
  }

  if (!is.na(pcid_choose)) {
    tickets = dplyr::filter(tickets, IOPAC %in% pcid_choose) # updated 03-01-21, was pcgroup %in% pcid_choose
  }

  if (any(!is.na(year_choose))) {
    tickets = dplyr::filter(tickets, crab_year %in% year_choose)
  }

  if (nrow(tickets) == 0) {
    return(NA)
  }
  # get total number of boats (MF 2/26/2019, JS/MF 1/27/21)
  fleet_size <- length(unique(filter(tickets, drvid != 'NONE')$drvid))

  # create a df with 2 columns: SPGRPN2 (metier.name in Mary's code) and max_boats, the maximum boats that participated in the metier during the specified year(s)
  n_boats <- tickets %>%
    filter(drvid != 'NONE') %>%
    group_by(crab_year, SPGRPN2) %>% #changed year to crab_year (MF 2/26/2019)
    summarise(n_boats = length(unique(drvid)), .groups = "drop") %>% #changed summarize to summarise, JS 11092018; added , .groups = "drop" 01-13-2022 JS
    group_by(SPGRPN2) %>%
    summarise(max_boats = max(n_boats), .groups = "drop") #changed summarize to summarise, JS; added , .groups = "drop" 01-13-2022 JS

  # create a df where each column is a SPGRPN2, and values represent the total revenue for a boat in a crab year from that SPGRPN2
  boats <- tickets %>%
    filter(drvid != 'NONE') %>%
    group_by(drvid, SPGRPN2, crab_year) %>% #removed mutate; changed year to crab_year MF 2/26/2019
    summarise(revenue = sum(adj_afi_revenue), .groups = "drop") %>% #changed summarize to summarise, JS 11092018; added , .groups = "drop" JS 01-13-2022; 12-31-2024 adj_revenue changed to adj_afi_revenue
    pivot_wider(names_from = SPGRPN2, values_from = revenue, values_fill = NA)
  boats <- as.data.frame(boats)
  rownames(boats) <- paste(boats$drvid, boats$crab_year, sep = "_")
  boats$drvid <- NULL
  boats$crab_year <- NULL

  # JS added 08302021 to avoid issue of filters leading to no boats that meet rev cutoffs
  if (is.null(nrow(boats)) == TRUE) {
    return(NA)
  }

  # remove the one boat that didn't sell catch (i.e. rev = 0). removed 08132021
  # if(any(rowSums(boats,na.rm=T)==0)){boats <- boats[-which(rowSums(boats, na.rm=T)==0),]}

  # remove boats that don't generate at least min_rev in revenue annually. added 08112021
  if (any(rowSums(boats, na.rm = T) < min_rev)) {
    boats <- boats[-which(rowSums(boats, na.rm = T) < min_rev), ]
  }

  # JS added 08302021 to avoid issue of filters leading to no boats that meet rev cutoffs
  if (is.null(nrow(boats)) == TRUE) {
    return(NA)
  }

  ##### calculate percent contributions, then remove fisheries with below min_rev_indiv #####
  # make a new df with annual % revenue from each metier for each boat
  percent_boats <- boats / rowSums(boats, na.rm = T)
  percent_boats_mat <- as.matrix(percent_boats)
  # for each boat, set percent_boats table value as "NA" for fisheries that don't generate at least min_rev_indiv in revenue annually. added 08192021
  percent_boats_mat[which(boats < min_rev_indiv)] <- NA
  percent_boats <- as.data.frame(
    percent_boats_mat,
    row.names = rownames(percent_boats_mat),
    col.names = colnames(percent_boats_mat)
  )
  rm(percent_boats_mat)
  # for each boat, set filtered_boats table value as "NA" for fisheries that don't generate at least min_rev_indiv in revenue annually.
  boats_mat <- as.matrix(boats)
  boats_mat[which(boats_mat < min_rev_indiv)] <- NA
  filtered_boats <- as.data.frame(
    boats_mat,
    row.names = rownames(boats_mat),
    col.names = colnames(boats_mat)
  )

  ##### OR remove fisheries first, then calculate percent contribution ##### -- hashed out by MF 08192021
  # for each boat, set table value as "NA" for fisheries that don't generate at least min_rev_indiv in revenue annually. added 08192021
  # if(any(boats < min_rev_indiv, na.rm=TRUE)){boats[which(boats < min_rev_indiv),] <- NA}

  #!! MF -- the above didn't work for me; I still have values < 500 in the matrix. I had to use the following code
  # boats_mat <- as.matrix(boats)
  # boats_mat[which(boats_mat<min_rev_indiv)] <- NA
  # boats <- as.data.frame(boats_mat, row.names=rownames(boats_mat), col.names=colnames(boats_mat))

  # boats <- boats %>%
  #   mutate(
  #     revenue = case_when(
  #     revenue < min_rev_indiv ~ NA,
  #     revenue == revenue
  #     )
  #   )

  # make a new df with annual % revenue from each metier for each boat
  # percent_boats <- boats/rowSums(boats, na.rm = T)

  # find median contribution of fisheries across vessels (with min_rev_indiv applied)
  percent_contribution = apply(percent_boats, MARGIN = 2, FUN = function(x) {
    median(x, na.rm = T)
  })

  # process data: drop metiers if fewer than 3 boats participate
  # in any year, and have to be on average (min_contribution*100)% of boats annual revenue
  if (filter) {
    nb = as.numeric(min_vessels) # changed from 3 to f(x) argument
    percent = as.numeric(min_contribution) # changed from 0.25 to f(x) argument
  } else {
    nb = 0
    percent = 0
  }

  # make a new df with median contribution of fisheries across vessels
  fishery_df = as.data.frame(percent_contribution)
  fishery_df$SPGRPN2 = rownames(fishery_df)
  rownames(fishery_df) <- NULL

  # make a new df with vessels per fishery
  fish_df <- left_join(fishery_df, n_boats, by = 'SPGRPN2')

  fisheries <- fish_df$SPGRPN2[which(
    fish_df$max_boats >= nb &
      fish_df$percent_contribution >= percent
  )] # updated 5/13/2019 from > to >=

  vessels <- fish_df$max_boats[which(
    fish_df$max_boats >= nb &
      fish_df$percent_contribution >= percent
  )] # added JS 01/26/2021

  vessel_df <- data.frame(v = fisheries, n = vessels) # added JS 01/27/2021

  if (length(fisheries) == 0) {
    return(NA)
  }

  # get total number of boats INCLUDED IN THE NETWORK - added MF 20210819
  network_fleet_size <- dim(percent_boats)[1]

  # build adjacency matrix
  A <- matrix(ncol = length(fisheries), nrow = length(fisheries), data = 0)
  colnames(A) <- fisheries
  rownames(A) <- fisheries

  if (edge_type == "connectivity") {
    #  matrix where elements are frac rev fishery i * frac rev fishery j * total dollars (sum)
    for (k in 1:nrow(boats)) {
      for (i in 1:nrow(A)) {
        frac_rev_i = percent_boats[k, fisheries[i]]
        if (is.na(frac_rev_i)) {
          next
        } # if don't fish this, then can skip all other combos

        for (j in i:ncol(A)) {
          frac_rev_j = percent_boats[k, fisheries[j]]
          if (is.na(frac_rev_j)) {
            next
          }

          total_rev = boats[k, fisheries[i]] + boats[k, fisheries[j]]
          A[i, j] = A[i, j] + frac_rev_i * frac_rev_j * total_rev
        }
      }
      #if(k %% 1000 == 0){cat(paste(' iteration', k))}
    } #end "connectivity"
  } else if (edge_type == "vessels") {
    #   matrix where elements are counts of vessels participating in fishery i & j
    for (k in 1:nrow(boats)) {
      for (i in 1:nrow(A)) {
        for (j in i:ncol(A)) {
          if (
            !is.na(percent_boats[k, fisheries[i]]) &
              !is.na(percent_boats[k, fisheries[j]])
          ) {
            A[i, j] = A[i, j] +
              as.numeric(
                tickets %>%
                  filter(SPGRPN2 == fisheries[i] | SPGRPN2 == fisheries[j]) %>%
                  group_by(crab_year) %>%
                  summarise(
                    n_boats = length(unique(drvid)),
                    .groups = "drop"
                  ) %>% # added , .groups = "drop" JS 01-13-2022
                  summarise(max_boats = max(n_boats), .groups = "drop") # added , .groups = "drop" JS 01-13-2022
              )
          }
        }
      }
      #if(k %% 1000 == 0){cat(paste(' iteration', k))}
    }
    A_counts <- A
    # matrix where elements are proportion of vessels participating in fishery i & j (out of total # vessels included in network)
    A_confidential <- A_counts / network_fleet_size
    # non-confidential version of matrix A
    A <- A_confidential
    A[which(A_counts < 3)] <- 0
  } else {
    stop("ERROR: unrecognized edge type; cannot generate input matrix.")
  }

  # if(write_out){
  # write.csv(A, here::here(out_dir,paste0("A_",state_choose, "_", year_choose,".csv")), row.names=FALSE)
  # }

  if (write_out & !is.na(pcid_choose)) {
    # added "& !is.na(pcid_choose)" 08202021
    if (edge_type == "connectivity") {
      write.csv(
        A,
        here::here(
          out_dir,
          paste0(
            "A_",
            pcid_choose,
            "_",
            year_choose,
            "_connectivity_",
            Sys.Date(),
            ".csv"
          )
        ),
        row.names = FALSE
      )
    } else if (edge_type == "vessels") {
      # write out both confidential and non-confidential versions of the A matrix.
      write.csv(
        A,
        here::here(
          out_dir,
          paste0(
            "A_",
            pcid_choose,
            "_",
            year_choose,
            "_vessels_",
            Sys.Date(),
            ".csv"
          )
        ),
        row.names = TRUE
      )
      write.csv(
        A_confidential,
        here::here(
          out_dir,
          paste0(
            "A_",
            pcid_choose,
            "_",
            year_choose,
            "_confidential_vessels_",
            Sys.Date(),
            ".csv"
          )
        ),
        row.names = TRUE
      )
    }
  }

  # added 08202021
  if (write_out & !is.na(state_choose)) {
    if (edge_type == "connectivity") {
      write.csv(
        A,
        here::here(
          out_dir,
          paste0("A_", state_choose, "_", year_choose, "_", Sys.Date(), ".csv")
        ),
        row.names = FALSE
      )
    } else if (edge_type == "vessels") {
      # write out both confidential and non-confidential versions of the A matrix.
      write.csv(
        A,
        here::here(
          out_dir,
          paste0("A_", state_choose, "_", year_choose, "_", Sys.Date(), ".csv")
        ),
        row.names = TRUE
      )
      write.csv(
        A_confidential,
        here::here(
          out_dir,
          paste0(
            "A_",
            state_choose,
            "_",
            year_choose,
            "_confidential_",
            Sys.Date(),
            ".csv"
          )
        ),
        row.names = TRUE
      )
    }
  }

  # create graph
  g <- graph_from_adjacency_matrix(
    adjmatrix = A,
    mode = 'undirected',
    weighted = TRUE,
    diag = FALSE
  )
  vertex_size = sum(boats[, fisheries], na.rm = T)
  V(g)$size <- vertex_size #total revenue in all fisheries
  V(g)$percent_size = apply(
    percent_boats[, fisheries, drop = FALSE],
    MARGIN = 2,
    FUN = function(x) median(x, na.rm = T)
  )
  V(g)$importance = V(g)$size * V(g)$percent_size #how much revenue from each fishery. note that the plot_networks.R function relies on the igraph library, which scales all nodes to the max size. so in practice, node size is based simply on percent_size and all node sizes are rellattive within a networ

  V(g)$fleet = fleet_size #total number of vessels active in given port group, fishing year (MF2/26/2019)

  vessel_df2 <- left_join(data.frame(v = V(g)$name), vessel_df, by = "v") # added JS 01/27/2021
  V(g)$vessels <- vessel_df2$n # added JS 01/27/2021
  #V(g)$vessels = vessels # added JS 01/26/2021, replaced with 2 lines above
  V(g)$total_vessels <- network_fleet_size #total number of vessels in network (differs from "fleet" attribute assigned on line ) - added MF 20210819

  ##########  changed 2/26/2019 ############
  # if filter_subgraph = TRUE, keep V which make up to 99% of revenue
  if (filter_subgraph) {
    if (length(V(g)) == 1) {
      big_g <- g
    } else {
      # calculate % cumulative revenue fisheries are responsible for
      size_df <- cbind(V(g), V(g)$importance) #changed from V(g)$size
      size_df <- size_df[order(size_df[, 2], decreasing = T), ]
      size_df <- cbind(size_df, cumsum(size_df[, 2]) / sum(size_df[, 2]))

      big_g <- induced_subgraph(
        g,
        V(g)[V(g)[rownames(size_df)[which(size_df[, 3] < .99)]]]
      ) #IS THIS KEEPING THE RIGHT VERTICES??
    }
  } else {
    big_g <- g
  }
  return(big_g)
}

```

Stats
```{r}
#' Calculate Network Statistics
#'
#' Calculate all network-level and node-level statistics for a given graph.
#'
#' @param g network, as an igraph object
#' @param y the year or crab year represented by the network
#' @param stats Specify whether you want to calculate node-level stats ('node'), network-level stats ('network') or both
#' @return data frame with statistics
#' @examples
#' stats.net <- net_stats(open_g, y = y, stats="network")
#' stats.node <- net_stats(open_g, y = y, stats="node")
#' stats.all <- net_stats(open_g, y = y, stats="both")
#' @export
net_stats <- function(g, y, stats="both"){
deg_norm = degree(g, normalized=TRUE) #get degree centralities
strength_rel = strength(g)/sum(E(g)$weight) #individual node strength
# by node
if(stats == "node" | stats == "both"){
  year <- rep(y, length(V(g)$name))
  node_strength = strength(g)/sum(E(g)$weight) #individual node strength
  eigen = eigen_centrality(g, weights = E(g)$weight)$vector #eigenvector centrality
  metier = V(g)$name
  gear=as.character(lapply(strsplit(metier,"_"), function(x){return(x[2])}))
  metier.cm = V(g)$common_name
  if(length(E(g)$weight) < 1){
    message("WARNING: No edges in this network.")
    btwn=NA
    btwn_inverted=NA
    basic_btwn =  betweenness(g, directed = FALSE, weights = NULL, normalized = TRUE)
  } else{
    ew = mean(E(g)$weight, na.rm = T)/E(g)$weight #in the betweenness function, edge weights are costs, not strengths.
    ew2 = 1/E(g)$weight
    btwn = betweenness(g, directed = FALSE, weights = ew, normalized = TRUE) #betweenness centrality
    btwn_inverted = betweenness(g, directed = FALSE, weights = ew2, normalized = TRUE)
    basic_btwn = betweenness(g, directed = FALSE, weights = E(g)$weight, normalized = TRUE)
  }
  
  node_stats <- as.data.frame(cbind(year, metier, gear, metier.cm, node_strength, eigen,btwn,btwn_inverted,basic_btwn,deg_norm))
}
if(stats=="network" | stats == "both"){
  # entire network 
  beta_eff = beta_eff(g)
  assort = assortativity_degree(g, directed = FALSE) #assortativity
  ld = length(E(g))/length(V(g)) #link density
  ed = edge_density(g) #edge density
  ed_weighted = sum(E(g)$weight)
  N = vcount(g) #number of metiers
  E = ecount(g) #number of edges
  if(E > 1){
    avg_ew = mean(E(g)$weight, na.rm = T) #average edge weight
    sd_ew = sd(E(g)$weight, na.rm = T)
    med_ew = median(E(g)$weight, na.rm = T) #median edge weight
    max_ew = max(E(g)$weight, na.rm = T) #maximum edge weight
    total_ew = sum(E(g)$weight, na.rm = T) #added MF 2/26/2019
    avg_ew_scaled = avg_ew/total_ew #added MF 2/26/2019  NEED TO EDIT DENOMINATOR
    sd_ew_scaled = sd_ew/total_ew #added MF 2/26/2019
    med_ew_scaled = med_ew/total_ew #added MF 2/26/2019
  } else{
    avg_ew = NA #average edge weight
    sd_ew = NA
    med_ew = NA #median edge weight
    max_ew = 0 #maximum edge weight
    avg_ew_scaled = NA
    sd_ew_scaled = NA
    med_ew_scaled = NA
  }
  deg_max = max(deg_norm) #max degree centrality
  deg_min = min(deg_norm) #min degree centrality
  mean_deg = (2*E)/N #mean degree, Lorien Jasny
  strength_mean = mean(strength_rel)
  nc = net_centr(g) #network centralization 
  nc_weighted = net_centr_weighted(g) #network centralization, weighted graph
  wtc <- cluster_walktrap(g, weights = E(g)$weight) #find densely connected subgraphs via random walk
  m <- modularity(g, membership(wtc)) #modularity
  m_weighted <- modularity(g, membership(wtc),weights=E(g)$weight) #modularity
  net_stats = as.data.frame(cbind(y,N,E, 
                                  avg_ew, sd_ew, med_ew, max_ew,
                                  avg_ew_scaled, sd_ew_scaled, med_ew_scaled,
                                  deg_max, deg_min, strength_mean,
                                  assort,ed,ld, mean_deg,
                                  nc,nc_weighted,
                                  m,m_weighted,
                                  beta_eff))
}
if(stats=="network"){
  return(net_stats)
} else if(stats=="node"){
  return(node_stats)
} else{
  return(list(node_stats, net_stats))
}
}
```

```{r}
#' @param g igraph object
#' @return numeric value
#' @examples
#' 
#' @export
beta_eff = function(g){
  if(is.null(E(g)$weight)){
    beta_eff = NA
  }else{
    beta_eff = mean(E(g)$weight) + var(E(g)$weight)/mean(E(g)$weight)
  }
  return(beta_eff)
}

net_centr = function(g){
  deg = degree(g)
  max_deg = max(deg)
  denom = (vcount(g) - 2) * (vcount(g) - 1)
  numer = 0
  for(d in deg){
    numer = numer + (max_deg - d)
  }
  return(numer/denom)
}

net_centr_weighted = function(g){
  deg=strength(g)
  max_deg=max(deg)
  pos_deg = deg[which(deg >0)]
  denom = ((vcount(g)-2)*(vcount(g)-1)) * mean(pos_deg)
  numer=0
  for(d in deg){
    numer = numer + (max_deg - d)
  }
  return(numer/denom)
}
```

## Create networks

```{r eval=TRUE}


# y=2019
# p = "AST"
# iopac = "Astoria"
# wc_state = "W"
for(y in years){
  for(iopac in myports){ # updated to iopac 03-10-21, was p
    cat(iopac, "\n")
    
    ### pull fish ticket data for given year, port group ###
    
    dat <- fishtix %>%
      #filter(crab_year == 2008 & IOPAC == "Bodega Bay") # this line is just for running through for loop manually
      filter(crab_year == y & IOPAC == iopac) 
    
    ##### Create igraph object ####
    
    ## using participation_network function *if write_out = true, set pcid_choose/year_choose to p/y for file naming!
    tmp_g <- participation_network_crabyear(
      dat, 
      filter = TRUE, filter_subgraph = FALSE,
      edge_type="connectivity", pcid_choose=iopac, state_choose = NA, year_choose=y, min_vessels = vessel_cutoff, min_contribution = contr_cutoff, min_rev = total_rev_cutoff, min_rev_indiv = indiv_rev_cutoff,
      write_out=FALSE)
    
    if(any(is.na(tmp_g))){
      message("\n\n WARNING: No fishing at ", iopac, " in crab year ", y, "!\n\n") # updated to iopac 03-10-21, was No fishing at ", p, "
    } else if(vcount(tmp_g) > 0){
      ## add in the full metier names as vertex attribute
      filtered_metier_info <- as.data.frame(x = V(tmp_g)$name)
      colnames(filtered_metier_info) <- "SPGRPN2" #"metier.abbrev"
      filtered_metier_info <- left_join(filtered_metier_info, node_names, by = "SPGRPN2")
      V(tmp_g)$common_name <- as.character(filtered_metier_info$species_group_2_label2)
      ## save vertex colors as attribute
      vertex_cols <- vertex_color(g = tmp_g)
      V(tmp_g)$colors <- vertex_cols
      ## save objects
      # rds_name <- ifelse(rm_crab,  paste0("igraph_", iopac, "_", y, "_totalrev", total_rev_cutoff,"_indivrev", indiv_rev_cutoff,"_", edgetype,"_rmCrab.rds"),  paste0("igraph_", iopac, "_", y, "_", total_rev_cutoff,"_", indiv_rev_cutoff,"_", edgetype,".rds")) # updated to iopac 03-10-21, was "igraph_", p
      # saveRDS(tmp_g, file = here::here(outdir_ports, rds_name))
      
    # Calculate node & network-level statistics
    ## using the `net_stats` function
    g_stats <- net_stats(tmp_g, y = y, stats="both") # ran first with this argument 12-29-2021
    g_nodestats <- g_stats[[1]]
    g_netstats <- g_stats[[2]]
      # g_stats <- net_stats(tmp_g, y = y, stats="node") # added 12-29-2021. ran second with this argument 12-29-2021
    #g_stats <- net_stats(tmp_g, y = 2008, stats="network")
    ## add on period (closure/open) and port group info
    g_netstats <- g_netstats %>%
      #mutate(period = rep("early", times=dim(g_stats)[1])) %>%
      mutate(pcgroup = rep(iopac, times=dim(g_netstats)[1])) # updated to iopac 03-10-21, was rep(p
    
    g_nodestats <- g_nodestats %>%
      mutate(pcgroup = rep(iopac, times=dim(g_nodestats)[1]))
  
    
    
    #### SAVE NETWORK STATS OUTPUT ####
    ## merge network stats from closure / open period
    # if(length(V(tmp_g)$name) == 0){
    #   tmp_stats <- g_stats
    # } else{
    #   tmp_stats <- rbind(g_stats, late_stats)
    # }
    ## append to network stats output data frame
    if(exists('mystats3')){
      mystats3 <- rbind(mystats3, g_netstats)
    } else{
      mystats3 <- g_netstats
    }
    if(exists('mystats4')){
      mystats4 <- rbind(mystats4, g_nodestats)
    } else{
      mystats4 <- g_nodestats
    }
    
    } #end 'else' close-g has > 0 vertex
  } #end (p in myports)
  cat("\nfinished with all port groups in crab year ", y, "\n-----\n")
} #end (y in years)
```

### 
# Tidy approach


